CC = gcc
CFLAGS = -Wall -Wextra
LIBS = -lm
EXECUTABLE = traitement_t

all: $(EXECUTABLE)

$(EXECUTABLE): main.c AVL_t.c AVL_t.h
	$(CC) $(CFLAGS) -o $@ main.c AVL_t.c $(LIBS)

clean:
	rm -f $(EXECUTABLE)





