CC = gcc
CFLAGS = -Wall -Wextra -std=c11
LDFLAGS =

SRC = main.c
OBJ = $(SRC:.c=.o)
EXEC = myprogram

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJ) $(EXEC)
